class AppSvg {
  AppSvg._();

  static const root = 'assets/svgs';
  static const all = '$root/all.svg';
  static const arrowFillRight = '$root/arrow-fill-right.svg';
  static const arrowFillLeft = '$root/arrow-fill-left.svg';
  static const arrowLeft = '$root/arrow_left.svg';
  static const arrowRight = '$root/arrow_right.svg';
  static const background = '$root/background.svg';
  static const boxCircleCheck = '$root/box_circle_check.svg';
  static const boxOpen = '$root/box_open.svg';
  static const checkCircle = '$root/check_circle.svg';
  static const chemistry = '$root/chemistry.svg';
  static const close = '$root/close.svg';
  static const percentage = '$root/percentage.svg';
  static const email = '$root/email.svg';
  static const exit = '$root/exit.svg';
  static const eye = '$root/eye.svg';
  static const eyeClose = '$root/eye_close.svg';
  static const facebook = '$root/facebook.svg';
  static const google = '$root/google.svg';
  static const heart = '$root/heart.svg';
  static const heartFill = '$root/heart_fill.svg';
  static const lock = '$root/lock.svg';
  static const logo = '$root/logo.svg';
  static const marker = '$root/marker.svg';
  static const minus = '$root/minus.svg';
  static const options = '$root/options.svg';
  static const phone = '$root/phone.svg';
  static const picture = '$root/picture.svg';
  static const pie = '$root/pie.svg';
  static const plus = '$root/plus.svg';
  static const search = '$root/search.svg';
  static const sent = '$root/sent.svg';
  static const shippingFast = '$root/shipping_fast.svg';
  static const shippingFastLeft = '$root/shipping-fast-left.svg';
  static const text = '$root/text.svg';
  static const timePast = '$root/time_past.svg';
  static const trash = '$root/trash.svg';
  static const user = '$root/user.svg';
  static const userPen = '$root/user-pen.svg';
}
